"""H2 - GCC stays ahead across deadline and retransmission settings.

This verifier matches the H2 page. It reads the page snapshot generated by
`h2_emit_snapshot.py` for the `retransmission-deadline-fluc` experiment and
checks the actual comparison: for every crossed deadline/retransmission cell,
GCC delivered more median viewer frames than SCReAM on the fluctuating network.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from analysis.hypotheses import _verifier as V  # noqa: E402

HID = "H2"
CLAIM = (
    "On the fluctuating network, GCC delivers more viewer frames than SCReAM "
    "across latency-deadline and retransmission settings"
)
SOURCE = "Project-internal fluctuating-network deadline/retransmission experiment"
SNAPSHOT = PROJECT_ROOT / "analysis" / "hypotheses" / "h2_data_retransmission-deadline-fluc.json"
EXPECTED_CELLS = 6
MIN_GCC_FRAME_ADVANTAGE = 30.0


def _load_snapshot() -> dict | None:
    if not SNAPSHOT.is_file():
        return None
    return json.loads(SNAPSHOT.read_text())


def main() -> None:
    V.print_header(HID, CLAIM, SOURCE)
    snapshot = _load_snapshot()
    if snapshot is None:
        return V.print_untested(
            "missing analysis/hypotheses/h2_data_retransmission-deadline-fluc.json; "
            "run h2_emit_snapshot.py first"
        )

    comparisons = snapshot.get("comparison") or []
    if len(comparisons) < EXPECTED_CELLS:
        return V.print_untested(
            f"need {EXPECTED_CELLS} comparison cells; found {len(comparisons)}"
        )

    numbers: dict[str, str] = {}
    supported_cells = 0
    advantages = []
    for cell in sorted(comparisons, key=lambda c: (int(c["budget_ms"]), bool(c["nack"]))):
        budget = int(cell["budget_ms"])
        nack = bool(cell["nack"])
        scream = float(cell["scream_median"])
        gcc = float(cell["gcc_median"])
        advantage = gcc - scream
        advantages.append(advantage)
        if advantage >= MIN_GCC_FRAME_ADVANTAGE:
            supported_cells += 1
        label = f"budget_{budget}_{'nack' if nack else 'no_retx'}"
        numbers[label] = (
            f"scream={scream:.1f}, gcc={gcc:.1f}, "
            f"gcc_advantage={advantage:.1f} frames"
        )

    if supported_cells == len(comparisons):
        verdict = "supported"
        note = (
            "GCC leads SCReAM in every tested deadline/retransmission cell; "
            f"minimum GCC median-frame advantage is {min(advantages):.1f}"
        )
    elif supported_cells:
        verdict = "inconclusive"
        note = "GCC leads in some cells, but not all cells meet the stated margin"
    else:
        verdict = "refuted"
        note = "GCC does not maintain the expected frame-delivery advantage"

    return V.print_verdict(verdict, numbers, note)


if __name__ == "__main__":
    main()
